spring.application.name=user-service
# Application Info
#spring.application.name=user-service


# Server Configuration
server.port=9999

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=yakobu@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Configuration
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.topic.user-registered=user_registered_topic

# Logging Configuration
logging.level.root=info

# =============================
# RABBITMQ CONFIGURATION
# =============================

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# (Optional)
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=60000

